public class ProfileConsts implements ConcreteConsts {
    public static final ProfileConsts INSTANCE = new ProfileConsts();

    public final Name NAME = new Name();

    public class Name {
        public final String ANALYTICS_CLOUD_INTEGRATION_USER = 'Analytics Cloud Integration User';
        public final String ANALYTICS_CLOUD_SECURITY_USER = 'Analytics Cloud Security User';
        public final String AUTHENTICATED_WEBSITE = 'Authenticated Website';
        public final String CHATTER_EXTERNAL_USER = 'Chatter External User';
        public final String CHATTER_FREE_USER = 'Chatter Free User';
        public final String CHATTER_MODERATOR_USER = 'Chatter Moderator User';
        public final String COMMUNITY_PROFILE = 'Community Profile';
        public final String CONTRACT_MANAGER = 'Contract Manager';
        public final String CROSS_ORG_DATA_PROXY_USER = 'Cross Org Data Proxy User';
        public final String CUSETOMER_PORTAL_MANAGER_CUSTOM = 'Customer Portal Manager Custom';
        public final String CUSTOMER_COMMUNITY_LOGIN_USER = 'Customer Community Login User';
        public final String CUSTOMER_COMMUNITY_PLUS_LOGIN_USER = 'Customer Community Plus Login User';
        public final String CUSTOMER_COMMUNITY_PLUS_USER = 'Customer Community Plus User';
        public final String CUSTOMER_COMMUNITY_USER = 'Customer Community User';
        public final String CUSTOMER_PORTAL_MANAGER_STANDARD = 'Customer Portal Manager Standard';
        public final String EXTERNAL_APPS_LOGIN_USER = 'External Apps Login User';
        public final String EXTERNAL_IDENTITY_USER = 'External Identity User';
        public final String FORCE_COM_APP_SUBSCRIPTION_USER = 'Force.com - App Subscription User';
        public final String FORCE_COM_FREE_USER = 'Force.com - Free User';
        public final String GOLD_PARTNER_USER = 'Gold Partner User';
        public final String HIGHT_VOLUMNE_CUSTOMER_PORTAL_USER = 'High Volume Customer Portal User';
        public final String HIGH_VOLUME_CUSTOMER_PORTAL = 'High Volume Customer Portal';
        public final String IDENTITY_USER = 'Identity User';
        public final String MARKETING_USER = 'Marketing User';
        public final String MINIMUM_ACCESS_SALESFORCE = 'Minimum Access - Salesforce';
        public final String PARTNER_APP_SUBSCRIPTION_USER = 'Partner App Subscription User';
        public final String PARTNER_COMMUNITY_LOGIN_USER = 'Partner Community Login User';
        public final String PARTNER_COMMUNITY_USER = 'Partner Community User';
        public final String READ_ONLY = 'Read Only';
        public final String SILVER_PARTNER_USER = 'Silver Partner User';
        public final String SOLUTION_MANAGER = 'Solution Manager';
        public final String STANDARD_GUEST = 'Standard Guest';
        public final String STANDARD_PLATFORM_USER = 'Standard Platform User';
        public final String STANDARD_USER = 'Standard User';
        public final String SYSTEM_ADMINSTRATOR = 'System Administrator';
        public final String WORK_COM_ONLY_USER = 'Work.com Only User';
    }
}
