public with sharing class Consts {

    public static final AccountConsts ACCOUNT {
        get {
            return AccountConsts.INSTANCE;
        }
    }

    public static final ContactConsts CONTACT {
        get {
            return ContactConsts.INSTANCE;
        }
    }

    public static final OpportunityConsts OPPORTUNITY {
        get {
            return OpportunityConsts.INSTANCE;
        }
    }

    public static final ProfileConsts PROFILE {
        get {
            return ProfileConsts.INSTANCE;
        }
    }
}
